# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install_end_test:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests!
      - run: yarn lint

  build:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - checkout
      # Restore cache of dependencies.
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      # Run build!
      - run: yarn build

      - save_cache:
          paths:
            - dist
          key: v1-dependencies-dist

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      # Restore folder "dist", which we built in previous task.
      - restore_cache:
          keys:
          - v1-dependencies-dist
      - run:
          name: Deploy to AWS S3
          command: |
            aws s3 sync --acl public-read --sse --delete dist/ s3://app-staging.e-commerce.cx

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install_end_test
      - build:
          requires:
            - install_end_test
          filters:
            branches:
              only: staging
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: staging
